Feature/ti 7 iniciar sesion, Authentication.
alanmoex/Turnos pull request #5
Opened 2024-09-11 18:54 UTC by N-Rem

2024-09-11 20:50 UTC, alanmoex requested changes
En gerenal la autenticación se ve correcta y funcional, solo se podria agregar un mejor manejo de excepciones cuando el usuario no es encontrado, o la contraseña ingresada es incorrecta.

2024-09-11 20:50 UTC, alanmoex commented on src/Infrastructure/Data/RepositoryUser.cs
> +                ?? throw new Exception("User not found");
Aqui es mejor utilizar la excepción personalizada NotFoundException que ya esta en el domain

2024-09-11 20:50 UTC, alanmoex commented on src/Infrastructure/Services/AuthenticationService.cs
> +                ?? throw new Exception("not found");
Aqui tambien se podria usar NotFoundException

2024-09-11 20:50 UTC, alanmoex commented on src/Infrastructure/Services/AuthenticationService.cs
> +        public string Authenticate (AuthenticationRequest authentucatuinRequest)
Se podria corregir el error tipográfico authentucatuinRequest a authenticationRequest

2024-09-11 20:50 UTC, alanmoex commented on src/Infrastructure/Services/AuthenticationService.cs
> +            claimsForToken.Add(new Claim("sub", user.Type.ToString()));
Aqui en vez de "sub" creo que deberia haber ido "role"

2024-09-11 20:50 UTC, alanmoex commented on src/WebApplication1/Controllers/AuthenticationController.cs
> +            return Ok(token);
Se podria agregar un try and catch para las excepciones, como la de usuario no encontrado.

2024-09-11 20:50 UTC, alanmoex commented on src/Infrastructure/Services/AuthenticationService.cs
> +                if (user.Password == authenticationRequest.Password) return user;
Aqui se podria agregar una excepción cuando el usuario es correcto pero la contraseña no.

2024-09-12 00:19 UTC, N-Rem commented on src/Infrastructure/Services/AuthenticationService.cs
> +                if (user.Password == authenticationRequest.Password) return user;
Eso se hace antes en GetByEmail( ). En la linea 40.

2024-09-12 15:18 UTC, JuaniTorti approved these changes

2024-09-12 15:52 UTC, alanmoex approved these changes

2024-09-12 15:53 UTC, merged